<?php
    define('DB_HOST','localhost');
    define('DB_USER','root');
    define('DB_PASS','AM13@t1k9');
    define('DB_NAME','apps_411');
    define('USER_TABLE','users');
    define('TRACKER_TABLE','tracker');
    define('BLACKLIST_TABLE','blacklist');
?>